### ISSUE TITLE
Duplicated tasks

### ISSUE THREAD

**Issue by blujaxfan** [lizard-heart/obsidian-to-omnifocus#3]
Version 1.1.16 (Installer 1.1.9), MacOS 13.3

I am getting duplicated text if I run the Extract command (Not using selected text, but the whole note). This behavior does not happen if I use the 'selected text' command. To me it appears the modified text is being inserted at the current cursor location, not replaced. 

## Here is the starting text in the note:

- [ ] This is a task #1

This is not a task

- [ ] This is a task #2

This is not another task
	This is indented text under not nother task

## Here is what is in the note after I run the command

- [ ] This is a task #1

This is not a task

- [ ] This is a task #2

This is not another task
	This is indented text under not nother task- [x] This is a task #1

This is not a task

- [x] This is a task #2

This is not another task
	This is indented text under not nother task

<img width="755" alt="Before" src="https://user-images.githubusercontent.com/60331895/232477099-7f7ccf7b-65a0-40f6-9b30-4c72bea0bb50.png">
<img width="737" alt="After" src="https://user-images.githubusercontent.com/60331895/232477134-d3d0bdac-edaf-401d-a21c-bac6cc230858.png">

**Comment by derrickwheals** [comment]
Same here

**Comment by lizard-heart** [comment]
Thank you for the issue. I will try to fix this as soon as possible.

**Comment by gregnewman** [comment]
I'm having the same problem.  If I turn off the option to mark complete after creating the tasks in OmniFocus it does not duplicate the page content.

**Comment by nweisenfeld** [comment]
If I understand it correctly, the issue is really that it uses "replaceSelection" regardless of whether it's operating on the selection or the whole text.  What that means is that the error is slightly more odd than just "duplicating" tasks.  Instead, the enter text is duplicated, with the tasks marked complete, and written over any selection in the editor.

Note that while I'm a seasoned software engineer, I'm not a Javascript programmer in any way, so please review my PR fully.

Here's a PR to address the issue: #5

**Comment by lizard-heart** [comment]
Alright, this issue seems to be fixed. Thanks for the pull request. Let me know if anyone here is still having issues.
